# Generated by Django 3.0.2 on 2020-01-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_poll_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_test',
            new_name='choice_text',
        ),
    ]
