# -*- coding: utf-8 -*-
"""Square of number using Map & Lambda function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xHj450Xpf9pa2uQwM0h_P7cgr0IJQGqw
"""

def SquareofSelfno(x):
  return x * x

lstNo = [3, 5, 7, 9, 111, 25681]

lstop = list(map(SquareofSelfno, lstNo))

lstop1 = list(map(lambda y: (y * y * y), lstNo))

print(lstop)

print(lstop1)